name: New Ubuntu Editor Version 🗔

on:
  workflow_dispatch: # This enables manual runs of the workflow

# Further reading:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event
# https://developer.github.com/webhooks/event-payloads/#repository_dispatch

jobs:
  buildImage:
    name: "🛠 Build unityci/editor (${{ matrix.targetPlatform }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - base # Base is a special name, which indicates that no modules are installed, like with linux-mono on ubuntu
          - linux-il2cpp
          - windows-mono
          - mac-mono
          - ios
          - android
          - webgl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add original repository as a remote
        run: |
          git remote add upstream https://github.com/game-ci/docker.git
          git fetch upstream --tags

      - name: Checkout latest release tag
        run: |
          git checkout tags/v3.1.0

      #############
      #   Setup   #
      #############
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #######################
      #   Free disk space   #
      #######################
      - name: Free disk space
        run: .github/workflows/scripts/free_disk_space.sh
      ############################
      #   Pull previous images   #
      ############################
      - name: Pull base image (must exist)
        run: docker pull unityci/base:3.1.0
      - name: Pull hub image (must exist)
        run: docker pull unityci/hub:3.1.0
      ###########################
      #   Ubuntu Editor image   #
      ###########################
      - name: Build and publish
        uses: docker/build-push-action@v5
        id: build_ubuntu_editor_image
        continue-on-error: true
        with:
          file: ./images/ubuntu/editor/Dockerfile
          build-args: |
            hubImage=unityci/hub:3.1.0
            baseImage=unityci/base:3.1.0
            version=2021.3.23f11
            changeSet=213b516bf396
            module=android
          push: false
